### ISSUE TITLE
OHNO! Discontinued!

### ISSUE THREAD

**Issue by hevnsnt** [sparkfun/H2OhNo#8]
OH NO!

Any chance you all have a stack of these boards laying around and I could buy 10+ off of you?

**Comment by bri-huang** [comment]
SparkFun provides the board files here. You can order these directly from OSHPark. If you haven't used their service, it's super easy and fast. For this size, it'll cost you just a bit more than $3 per board.

https://oshpark.com/shared_projects/DJ5Fg307

**Comment by loricrotser** [comment]
@hevnsnt 

Hi! I am closing this issue but please do let us know if you have any more questions! 
Thank you!
